#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Official entry point: Xiaoha cleaner with full owned-SQL removal.

This layer deliberately promotes every table found in CREATE TABLE statements
inside an owned Xiaoha/HGAdmin resource to the active DROP list.  It also
reverses ALTER TABLE ... ADD COLUMN statements on pre-existing tables.
"""

from __future__ import print_function

import re
import sys

import xiaoha_cleaner as core


ALTER_ADD_COLUMN_RE = re.compile(
    r"(?is)\bALTER\s+TABLE\s+[`\"']?([A-Za-z_][A-Za-z0-9_$]*)[`\"']?"
    r"\s+ADD\s+(?:COLUMN\s+)?(?:IF\s+NOT\s+EXISTS\s+)?"
    r"[`\"']?([A-Za-z_][A-Za-z0-9_$]*)"
)

_base_collect_sql_tables = core.collect_sql_tables
_base_build_plan = core.build_plan
_base_markdown_report = core.markdown_report


def collect_all_owned_sql(owned_roots, target):
    result = _base_collect_sql_tables(owned_roots, target)
    created_tables = set()
    added_columns = set()

    for root in owned_roots:
        for path in core.iter_files(root):
            if path.suffix.lower() not in {".lua", ".js", ".cjs", ".mjs", ".ts", ".sql"}:
                continue
            try:
                if path.stat().st_size > 8 * 1024 * 1024:
                    continue
                text, _, _ = core.read_text_file(path)
            except OSError:
                continue
            created_tables.update(
                table.lower() for table in core.SQL_CREATE_TABLE_RE.findall(text)
            )
            added_columns.update(
                (table.lower(), column.lower())
                for table, column in ALTER_ADD_COLUMN_RE.findall(text)
            )

    active_tables = set(result["safe_tables"])
    active_tables.update(created_tables)
    result["safe_tables"] = sorted(active_tables)
    result["created_tables"] = sorted(created_tables)
    result["review_tables"] = sorted(
        table for table in result["review_tables"] if table not in active_tables
    )
    result["added_columns"] = [
        {"table": table, "column": column}
        for table, column in sorted(added_columns)
        if table not in active_tables
    ]
    return result


def build_all_sql_plan(target, include_review=False):
    plan = _base_build_plan(target, include_review=include_review)
    plan["summary"]["added_sql_columns"] = len(plan["sql"]["added_columns"])
    return plan


def quote_identifier(value):
    return value.replace("`", "``")


def quote_literal(value):
    return value.replace("'", "''")


def database_cleanup_sql(plan):
    tables = plan["sql"]["safe_tables"]
    columns = plan["sql"].get("added_columns", [])
    review = plan["sql"]["review_tables"]
    lines = [
        "-- Generated by FiveM Xiaoha Cleaner {} at {}".format(core.VERSION, core.now_iso()),
        "-- Target: {}".format(plan["target"]),
        "-- Aggressive owned-SQL mode requested by the operator.",
        "-- Every CREATE TABLE found in an owned Xiaoha/HGAdmin resource is active.",
        "-- Back up the database before executing this file.",
        "",
        "SET @XIAOHA_OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "",
        "-- Tables created or clearly owned by Xiaoha/HGAdmin resources",
    ]
    if tables:
        for table in tables:
            lines.append("DROP TABLE IF EXISTS `{}`;".format(quote_identifier(table)))
    else:
        lines.append("-- None detected.")

    lines.extend(["", "-- Columns added by Xiaoha/HGAdmin to pre-existing tables"])
    if columns:
        for item in columns:
            table = quote_identifier(item["table"])
            column = quote_identifier(item["column"])
            lines.extend([
                "SET @XIAOHA_DROP_COLUMN = IF(",
                "  EXISTS(SELECT 1 FROM information_schema.COLUMNS",
                "    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '{}' AND COLUMN_NAME = '{}'),".format(
                    quote_literal(item["table"]), quote_literal(item["column"])
                ),
                "  'ALTER TABLE `{}` DROP COLUMN `{}`',".format(table, column),
                "  'SELECT 1'",
                ");",
                "PREPARE XIAOHA_DROP_STMT FROM @XIAOHA_DROP_COLUMN;",
                "EXECUTE XIAOHA_DROP_STMT;",
                "DEALLOCATE PREPARE XIAOHA_DROP_STMT;",
                "",
            ])
    else:
        lines.append("-- None detected.")

    lines.extend(["", "-- Referenced but not proven created; retained for audit only."])
    if review:
        for table in review:
            lines.append("-- DROP TABLE IF EXISTS `{}`;".format(quote_identifier(table)))
    else:
        lines.append("-- None detected.")
    lines.extend([
        "",
        "SET FOREIGN_KEY_CHECKS = @XIAOHA_OLD_FOREIGN_KEY_CHECKS;",
        "",
    ])
    return "\n".join(lines)


def markdown_report(
    plan, status="scan", operations=None, error=None,
    database_execution=None, notices=None,
    terminal=True, finished_at=None,
):
    text = _base_markdown_report(
        plan, status, operations, error, database_execution, notices,
        terminal, finished_at,
    )
    text = text.replace("可安全清理数据库表", "将删除的数据库表")
    text = text.replace("自动清理范围", "自动删除（资源内 CREATE TABLE 或明确归属）")
    text = text.replace(
        "仅人工复核（SQL 中保持注释）",
        "仅有引用、未证明由资源创建（SQL 中保持注释）",
    )
    marker = "- 外部代码引用："
    if marker in text:
        text = text.replace(
            marker,
            "- 将回滚的新增数据库列：{}\n{}".format(
                plan["summary"].get("added_sql_columns", 0), marker
            ),
            1,
        )
    return text


def print_summary(plan):
    core.print_summary(plan)
    print("Added SQL columns to remove: {}".format(
        plan["summary"].get("added_sql_columns", 0)
    ))


core.collect_sql_tables = collect_all_owned_sql
core.build_plan = build_all_sql_plan
core.database_cleanup_sql = database_cleanup_sql
core.markdown_report = markdown_report
core.print_summary = print_summary


if __name__ == "__main__":
    sys.exit(core.main())
